version: '3.9'

services:
  db: 
    container_name: postgres_assignments
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_assignments

volumes:
  postgres_data:
